### ISSUE TITLE
Recommendation Like Dislike Reopening Result

### ISSUE THREAD

**Issue by denizdikbiyik** [denizdikbiyik/SWE574Project#387] opened 2022-05-23 16:17 UTC
Recommendation after like dislike, show if like or dislike done before. Otherwise, do not show buttons after feedback given.

**Comment by emreerkaslan** [comment] 2022-05-23 23:20
Duplicate of: https://github.com/denizdikbiyik/SWE574Project/issues/366

**Closed by emreerkaslan** 2022-05-23 23:20 UTC
Labels: backend, Effort (Difficult)
